// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ActiveTaskHandlerHandler(ReducerEventContext ctx, ActiveTasks activeTask);
        public event ActiveTaskHandlerHandler? OnActiveTaskHandler;

        public void ActiveTaskHandler(ActiveTasks activeTask)
        {
            conn.InternalCallReducer(new Reducer.ActiveTaskHandler(activeTask), this.SetCallReducerFlags.ActiveTaskHandlerFlags);
        }

        public bool InvokeActiveTaskHandler(ReducerEventContext ctx, Reducer.ActiveTaskHandler args)
        {
            if (OnActiveTaskHandler == null) return false;
            OnActiveTaskHandler(
                ctx,
                args.ActiveTask
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ActiveTaskHandler : Reducer, IReducerArgs
        {
            [DataMember(Name = "activeTask")]
            public ActiveTasks ActiveTask;

            public ActiveTaskHandler(ActiveTasks ActiveTask)
            {
                this.ActiveTask = ActiveTask;
            }

            public ActiveTaskHandler()
            {
                this.ActiveTask = new();
            }

            string IReducerArgs.ReducerName => "ActiveTaskHandler";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ActiveTaskHandlerFlags;
        public void ActiveTaskHandler(CallReducerFlags flags) => ActiveTaskHandlerFlags = flags;
    }
}
