// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddItemTableItemHandler(ReducerEventContext ctx, ItemTable item);
        public event AddItemTableItemHandler? OnAddItemTableItem;

        public void AddItemTableItem(ItemTable item)
        {
            conn.InternalCallReducer(new Reducer.AddItemTableItem(item), this.SetCallReducerFlags.AddItemTableItemFlags);
        }

        public bool InvokeAddItemTableItem(ReducerEventContext ctx, Reducer.AddItemTableItem args)
        {
            if (OnAddItemTableItem == null) return false;
            OnAddItemTableItem(
                ctx,
                args.Item
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddItemTableItem : Reducer, IReducerArgs
        {
            [DataMember(Name = "item")]
            public ItemTable Item;

            public AddItemTableItem(ItemTable Item)
            {
                this.Item = Item;
            }

            public AddItemTableItem()
            {
                this.Item = new();
            }

            string IReducerArgs.ReducerName => "AddItemTableItem";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AddItemTableItemFlags;
        public void AddItemTableItem(CallReducerFlags flags) => AddItemTableItemFlags = flags;
    }
}
