// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddSkillTableSkillHandler(ReducerEventContext ctx, SkillTable skill);
        public event AddSkillTableSkillHandler? OnAddSkillTableSkill;

        public void AddSkillTableSkill(SkillTable skill)
        {
            conn.InternalCallReducer(new Reducer.AddSkillTableSkill(skill), this.SetCallReducerFlags.AddSkillTableSkillFlags);
        }

        public bool InvokeAddSkillTableSkill(ReducerEventContext ctx, Reducer.AddSkillTableSkill args)
        {
            if (OnAddSkillTableSkill == null) return false;
            OnAddSkillTableSkill(
                ctx,
                args.Skill
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddSkillTableSkill : Reducer, IReducerArgs
        {
            [DataMember(Name = "skill")]
            public SkillTable Skill;

            public AddSkillTableSkill(SkillTable Skill)
            {
                this.Skill = Skill;
            }

            public AddSkillTableSkill()
            {
                this.Skill = new();
            }

            string IReducerArgs.ReducerName => "AddSkillTableSkill";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AddSkillTableSkillFlags;
        public void AddSkillTableSkill(CallReducerFlags flags) => AddSkillTableSkillFlags = flags;
    }
}
