// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddStatsTableStatHandler(ReducerEventContext ctx, StatTable stat);
        public event AddStatsTableStatHandler? OnAddStatsTableStat;

        public void AddStatsTableStat(StatTable stat)
        {
            conn.InternalCallReducer(new Reducer.AddStatsTableStat(stat), this.SetCallReducerFlags.AddStatsTableStatFlags);
        }

        public bool InvokeAddStatsTableStat(ReducerEventContext ctx, Reducer.AddStatsTableStat args)
        {
            if (OnAddStatsTableStat == null) return false;
            OnAddStatsTableStat(
                ctx,
                args.Stat
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddStatsTableStat : Reducer, IReducerArgs
        {
            [DataMember(Name = "stat")]
            public StatTable Stat;

            public AddStatsTableStat(StatTable Stat)
            {
                this.Stat = Stat;
            }

            public AddStatsTableStat()
            {
                this.Stat = new();
            }

            string IReducerArgs.ReducerName => "AddStatsTableStat";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AddStatsTableStatFlags;
        public void AddStatsTableStat(CallReducerFlags flags) => AddStatsTableStatFlags = flags;
    }
}
