// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddTaskTableTaskHandler(ReducerEventContext ctx, TaskTable task, System.Collections.Generic.List<TaskRequirementTable> requirements, System.Collections.Generic.List<TaskRewardTable> reward);
        public event AddTaskTableTaskHandler? OnAddTaskTableTask;

        public void AddTaskTableTask(TaskTable task, System.Collections.Generic.List<TaskRequirementTable> requirements, System.Collections.Generic.List<TaskRewardTable> reward)
        {
            conn.InternalCallReducer(new Reducer.AddTaskTableTask(task, requirements, reward), this.SetCallReducerFlags.AddTaskTableTaskFlags);
        }

        public bool InvokeAddTaskTableTask(ReducerEventContext ctx, Reducer.AddTaskTableTask args)
        {
            if (OnAddTaskTableTask == null) return false;
            OnAddTaskTableTask(
                ctx,
                args.Task,
                args.Requirements,
                args.Reward
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddTaskTableTask : Reducer, IReducerArgs
        {
            [DataMember(Name = "task")]
            public TaskTable Task;
            [DataMember(Name = "requirements")]
            public System.Collections.Generic.List<TaskRequirementTable> Requirements;
            [DataMember(Name = "reward")]
            public System.Collections.Generic.List<TaskRewardTable> Reward;

            public AddTaskTableTask(
                TaskTable Task,
                System.Collections.Generic.List<TaskRequirementTable> Requirements,
                System.Collections.Generic.List<TaskRewardTable> Reward
            )
            {
                this.Task = Task;
                this.Requirements = Requirements;
                this.Reward = Reward;
            }

            public AddTaskTableTask()
            {
                this.Task = new();
                this.Requirements = new();
                this.Reward = new();
            }

            string IReducerArgs.ReducerName => "AddTaskTableTask";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AddTaskTableTaskFlags;
        public void AddTaskTableTask(CallReducerFlags flags) => AddTaskTableTaskFlags = flags;
    }
}
