// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddTexturesTextureHandler(ReducerEventContext ctx, Textures texture);
        public event AddTexturesTextureHandler? OnAddTexturesTexture;

        public void AddTexturesTexture(Textures texture)
        {
            conn.InternalCallReducer(new Reducer.AddTexturesTexture(texture), this.SetCallReducerFlags.AddTexturesTextureFlags);
        }

        public bool InvokeAddTexturesTexture(ReducerEventContext ctx, Reducer.AddTexturesTexture args)
        {
            if (OnAddTexturesTexture == null) return false;
            OnAddTexturesTexture(
                ctx,
                args.Texture
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddTexturesTexture : Reducer, IReducerArgs
        {
            [DataMember(Name = "texture")]
            public Textures Texture;

            public AddTexturesTexture(Textures Texture)
            {
                this.Texture = Texture;
            }

            public AddTexturesTexture()
            {
                this.Texture = new();
            }

            string IReducerArgs.ReducerName => "AddTexturesTexture";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AddTexturesTextureFlags;
        public void AddTexturesTexture(CallReducerFlags flags) => AddTexturesTextureFlags = flags;
    }
}
