// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteCharacterHandler(ReducerEventContext ctx, string name);
        public event DeleteCharacterHandler? OnDeleteCharacter;

        public void DeleteCharacter(string name)
        {
            conn.InternalCallReducer(new Reducer.DeleteCharacter(name), this.SetCallReducerFlags.DeleteCharacterFlags);
        }

        public bool InvokeDeleteCharacter(ReducerEventContext ctx, Reducer.DeleteCharacter args)
        {
            if (OnDeleteCharacter == null) return false;
            OnDeleteCharacter(
                ctx,
                args.Name
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteCharacter : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;

            public DeleteCharacter(string Name)
            {
                this.Name = Name;
            }

            public DeleteCharacter()
            {
                this.Name = "";
            }

            string IReducerArgs.ReducerName => "DeleteCharacter";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DeleteCharacterFlags;
        public void DeleteCharacter(CallReducerFlags flags) => DeleteCharacterFlags = flags;
    }
}
