// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ModToolHandler(ReducerEventContext ctx, string command, System.Collections.Generic.List<string> args);
        public event ModToolHandler? OnModTool;

        public void ModTool(string command, System.Collections.Generic.List<string> args)
        {
            conn.InternalCallReducer(new Reducer.ModTool(command, args), this.SetCallReducerFlags.ModToolFlags);
        }

        public bool InvokeModTool(ReducerEventContext ctx, Reducer.ModTool args)
        {
            if (OnModTool == null) return false;
            OnModTool(
                ctx,
                args.Command,
                args.Args
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ModTool : Reducer, IReducerArgs
        {
            [DataMember(Name = "command")]
            public string Command;
            [DataMember(Name = "args")]
            public System.Collections.Generic.List<string> Args;

            public ModTool(
                string Command,
                System.Collections.Generic.List<string> Args
            )
            {
                this.Command = Command;
                this.Args = Args;
            }

            public ModTool()
            {
                this.Command = "";
                this.Args = new();
            }

            string IReducerArgs.ReducerName => "ModTool";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ModToolFlags;
        public void ModTool(CallReducerFlags flags) => ModToolFlags = flags;
    }
}
