// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SendChatMessageHandler(ReducerEventContext ctx, string charName, string text);
        public event SendChatMessageHandler? OnSendChatMessage;

        public void SendChatMessage(string charName, string text)
        {
            conn.InternalCallReducer(new Reducer.SendChatMessage(charName, text), this.SetCallReducerFlags.SendChatMessageFlags);
        }

        public bool InvokeSendChatMessage(ReducerEventContext ctx, Reducer.SendChatMessage args)
        {
            if (OnSendChatMessage == null) return false;
            OnSendChatMessage(
                ctx,
                args.CharName,
                args.Text
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SendChatMessage : Reducer, IReducerArgs
        {
            [DataMember(Name = "charName")]
            public string CharName;
            [DataMember(Name = "text")]
            public string Text;

            public SendChatMessage(
                string CharName,
                string Text
            )
            {
                this.CharName = CharName;
                this.Text = Text;
            }

            public SendChatMessage()
            {
                this.CharName = "";
                this.Text = "";
            }

            string IReducerArgs.ReducerName => "SendChatMessage";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SendChatMessageFlags;
        public void SendChatMessage(CallReducerFlags flags) => SendChatMessageFlags = flags;
    }
}
