// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetUserNameHandler(ReducerEventContext ctx, string name);
        public event SetUserNameHandler? OnSetUserName;

        public void SetUserName(string name)
        {
            conn.InternalCallReducer(new Reducer.SetUserName(name), this.SetCallReducerFlags.SetUserNameFlags);
        }

        public bool InvokeSetUserName(ReducerEventContext ctx, Reducer.SetUserName args)
        {
            if (OnSetUserName == null) return false;
            OnSetUserName(
                ctx,
                args.Name
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetUserName : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;

            public SetUserName(string Name)
            {
                this.Name = Name;
            }

            public SetUserName()
            {
                this.Name = "";
            }

            string IReducerArgs.ReducerName => "SetUserName";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SetUserNameFlags;
        public void SetUserName(CallReducerFlags flags) => SetUserNameFlags = flags;
    }
}
