// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StartActiveTaksHandler(ReducerEventContext ctx, uint characterId, uint taskId);
        public event StartActiveTaksHandler? OnStartActiveTaks;

        public void StartActiveTaks(uint characterId, uint taskId)
        {
            conn.InternalCallReducer(new Reducer.StartActiveTaks(characterId, taskId), this.SetCallReducerFlags.StartActiveTaksFlags);
        }

        public bool InvokeStartActiveTaks(ReducerEventContext ctx, Reducer.StartActiveTaks args)
        {
            if (OnStartActiveTaks == null) return false;
            OnStartActiveTaks(
                ctx,
                args.CharacterId,
                args.TaskId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StartActiveTaks : Reducer, IReducerArgs
        {
            [DataMember(Name = "characterID")]
            public uint CharacterId;
            [DataMember(Name = "taskID")]
            public uint TaskId;

            public StartActiveTaks(
                uint CharacterId,
                uint TaskId
            )
            {
                this.CharacterId = CharacterId;
                this.TaskId = TaskId;
            }

            public StartActiveTaks()
            {
            }

            string IReducerArgs.ReducerName => "StartActiveTaks";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags StartActiveTaksFlags;
        public void StartActiveTaks(CallReducerFlags flags) => StartActiveTaksFlags = flags;
    }
}
