// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void WriteToLogsHandler(ReducerEventContext ctx, string text);
        public event WriteToLogsHandler? OnWriteToLogs;

        public void WriteToLogs(string text)
        {
            conn.InternalCallReducer(new Reducer.WriteToLogs(text), this.SetCallReducerFlags.WriteToLogsFlags);
        }

        public bool InvokeWriteToLogs(ReducerEventContext ctx, Reducer.WriteToLogs args)
        {
            if (OnWriteToLogs == null) return false;
            OnWriteToLogs(
                ctx,
                args.Text
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class WriteToLogs : Reducer, IReducerArgs
        {
            [DataMember(Name = "text")]
            public string Text;

            public WriteToLogs(string Text)
            {
                this.Text = Text;
            }

            public WriteToLogs()
            {
                this.Text = "";
            }

            string IReducerArgs.ReducerName => "WriteToLogs";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags WriteToLogsFlags;
        public void WriteToLogs(CallReducerFlags flags) => WriteToLogsFlags = flags;
    }
}
