// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Godot;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BaseExpTable: RefCounted
    {
        [DataMember(Name = "Level")]
        public uint Level;
        [DataMember(Name = "Exp")]
        public ulong Exp;

        public BaseExpTable(
            uint Level,
            ulong Exp
        )
        {
            this.Level = Level;
            this.Exp = Exp;
        }

        public BaseExpTable()
        {
        }
    }
}
