// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Godot;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CharacterStats: RefCounted
    {
        [DataMember(Name = "rowID")]
        public uint RowId;
        [DataMember(Name = "CharacterID")]
        public uint CharacterId;
        [DataMember(Name = "StatID")]
        public uint StatId;
        [DataMember(Name = "Level")]
        public uint Level;
        [DataMember(Name = "Exp")]
        public uint Exp;

        public CharacterStats(
            uint RowId,
            uint CharacterId,
            uint StatId,
            uint Level,
            uint Exp
        )
        {
            this.RowId = RowId;
            this.CharacterId = CharacterId;
            this.StatId = StatId;
            this.Level = Level;
            this.Exp = Exp;
        }

        public CharacterStats()
        {
        }
    }
}
