// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Godot;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CharacterInventory: RefCounted
    {
        [DataMember(Name = "rowID")]
        public ulong RowId;
        [DataMember(Name = "CharacterID")]
        public uint CharacterId;
        [DataMember(Name = "ItemID")]
        public uint ItemId;
        [DataMember(Name = "Amount")]
        public uint Amount;

        public CharacterInventory(
            ulong RowId,
            uint CharacterId,
            uint ItemId,
            uint Amount
        )
        {
            this.RowId = RowId;
            this.CharacterId = CharacterId;
            this.ItemId = ItemId;
            this.Amount = Amount;
        }

        public CharacterInventory()
        {
        }
    }
}
