// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Godot;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Character: RefCounted
    {
        [DataMember(Name = "CharacterID")]
        public uint CharacterId;
        [DataMember(Name = "Name")]
        public string Name;
        [DataMember(Name = "UserId")]
        public uint UserId;
        [DataMember(Name = "Online")]
        public bool Online;
        [DataMember(Name = "CreationDate")]
        public SpacetimeDB.Timestamp CreationDate;
        [DataMember(Name = "LastLoginDate")]
        public SpacetimeDB.Timestamp LastLoginDate;
        [DataMember(Name = "PlayTime")]
        public SpacetimeDB.TimeDuration PlayTime;

        public Character(
            uint CharacterId,
            string Name,
            uint UserId,
            bool Online,
            SpacetimeDB.Timestamp CreationDate,
            SpacetimeDB.Timestamp LastLoginDate,
            SpacetimeDB.TimeDuration PlayTime
        )
        {
            this.CharacterId = CharacterId;
            this.Name = Name;
            this.UserId = UserId;
            this.Online = Online;
            this.CreationDate = CreationDate;
            this.LastLoginDate = LastLoginDate;
            this.PlayTime = PlayTime;
        }

        public Character()
        {
            this.Name = "";
        }
    }
}
