// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Godot;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CharacterSkills: RefCounted
    {
        [DataMember(Name = "rowID")]
        public uint RowId;
        [DataMember(Name = "CharacterID")]
        public uint CharacterId;
        [DataMember(Name = "SkillID")]
        public uint SkillId;
        [DataMember(Name = "Level")]
        public uint Level;
        [DataMember(Name = "Exp")]
        public uint Exp;

        public CharacterSkills(
            uint RowId,
            uint CharacterId,
            uint SkillId,
            uint Level,
            uint Exp
        )
        {
            this.RowId = RowId;
            this.CharacterId = CharacterId;
            this.SkillId = SkillId;
            this.Level = Level;
            this.Exp = Exp;
        }

        public CharacterSkills()
        {
        }
    }
}
