// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Godot;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DisallowedWords: RefCounted
    {
        [DataMember(Name = "Word")]
        public string Word;
        [DataMember(Name = "id")]
        public uint Id;

        public DisallowedWords(
            string Word,
            uint Id
        )
        {
            this.Word = Word;
            this.Id = Id;
        }

        public DisallowedWords()
        {
            this.Word = "";
        }
    }
}
