// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Godot;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ItemRequirementType: RefCounted
    {
        [DataMember(Name = "ID")]
        public uint Id;
        [DataMember(Name = "Amount")]
        public uint Amount;

        public ItemRequirementType(
            uint Id,
            uint Amount
        )
        {
            this.Id = Id;
            this.Amount = Amount;
        }

        public ItemRequirementType()
        {
        }
    }
}
