// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Godot;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LevelRequirementType: RefCounted
    {
        [DataMember(Name = "ID")]
        public uint Id;
        [DataMember(Name = "Level")]
        public uint Level;

        public LevelRequirementType(
            uint Id,
            uint Level
        )
        {
            this.Id = Id;
            this.Level = Level;
        }

        public LevelRequirementType()
        {
        }
    }
}
