// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Godot;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Message: RefCounted
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "CharacterID")]
        public uint CharacterId;
        [DataMember(Name = "CharacterName")]
        public string? CharacterName;
        [DataMember(Name = "Sent")]
        public SpacetimeDB.Timestamp Sent;
        [DataMember(Name = "Text")]
        public string Text;

        public Message(
            uint Id,
            uint CharacterId,
            string? CharacterName,
            SpacetimeDB.Timestamp Sent,
            string Text
        )
        {
            this.Id = Id;
            this.CharacterId = CharacterId;
            this.CharacterName = CharacterName;
            this.Sent = Sent;
            this.Text = Text;
        }

        public Message()
        {
            this.Text = "";
        }
    }
}
