// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Godot;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ModCommands: RefCounted
    {
        [DataMember(Name = "command")]
        public string Command;
        [DataMember(Name = "token")]
        public string Token;

        public ModCommands(
            string Command,
            string Token
        )
        {
            this.Command = Command;
            this.Token = Token;
        }

        public ModCommands()
        {
            this.Command = "";
            this.Token = "";
        }
    }
}
