// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Godot;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class StatTable: RefCounted
    {
        [DataMember(Name = "StatID")]
        public uint StatId;
        [DataMember(Name = "TextureID")]
        public uint TextureId;
        [DataMember(Name = "Name")]
        public string Name;
        [DataMember(Name = "Description")]
        public string? Description;
        [DataMember(Name = "FunctionName")]
        public string? FunctionName;
        [DataMember(Name = "MaxLevel")]
        public uint MaxLevel;
        [DataMember(Name = "LevelScale")]
        public uint LevelScale;
        [DataMember(Name = "ExpScale")]
        public uint ExpScale;
        [DataMember(Name = "UseExpScale")]
        public uint UseExpScale;

        public StatTable(
            uint StatId,
            uint TextureId,
            string Name,
            string? Description,
            string? FunctionName,
            uint MaxLevel,
            uint LevelScale,
            uint ExpScale,
            uint UseExpScale
        )
        {
            this.StatId = StatId;
            this.TextureId = TextureId;
            this.Name = Name;
            this.Description = Description;
            this.FunctionName = FunctionName;
            this.MaxLevel = MaxLevel;
            this.LevelScale = LevelScale;
            this.ExpScale = ExpScale;
            this.UseExpScale = UseExpScale;
        }

        public StatTable()
        {
            this.Name = "";
        }
    }
}
