// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Godot;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SubMessage: RefCounted
    {
        [DataMember(Name = "Text")]
        public string Text;
        [DataMember(Name = "Sender")]
        public SpacetimeDB.Identity Sender;
        [DataMember(Name = "SendDate")]
        public SpacetimeDB.Timestamp SendDate;

        public SubMessage(
            string Text,
            SpacetimeDB.Identity Sender,
            SpacetimeDB.Timestamp SendDate
        )
        {
            this.Text = Text;
            this.Sender = Sender;
            this.SendDate = SendDate;
        }

        public SubMessage()
        {
            this.Text = "";
        }
    }
}
