// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Godot;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TaskRequirementTable: RefCounted
    {
        [DataMember(Name = "RowID")]
        public uint RowId;
        [DataMember(Name = "TaskID")]
        public uint TaskId;
        [DataMember(Name = "Type")]
        public string Type;
        [DataMember(Name = "ID")]
        public uint Id;
        [DataMember(Name = "Amount")]
        public uint Amount;

        public TaskRequirementTable(
            uint RowId,
            uint TaskId,
            string Type,
            uint Id,
            uint Amount
        )
        {
            this.RowId = RowId;
            this.TaskId = TaskId;
            this.Type = Type;
            this.Id = Id;
            this.Amount = Amount;
        }

        public TaskRequirementTable()
        {
            this.Type = "";
        }
    }
}
