// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Godot;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TaskTable: RefCounted
    {
        [DataMember(Name = "RowID")]
        public uint RowId;
        [DataMember(Name = "TaskID")]
        public uint TaskId;
        [DataMember(Name = "Name")]
        public string Name;
        [DataMember(Name = "Description")]
        public string? Description;
        [DataMember(Name = "Type")]
        public string? Type;
        [DataMember(Name = "LevelExpReward")]
        public uint LevelExpReward;
        [DataMember(Name = "SkillExpReward")]
        public uint SkillExpReward;
        [DataMember(Name = "ItemRewards")]
        public System.Collections.Generic.List<uint> ItemRewards;
        [DataMember(Name = "CompletionTime")]
        public SpacetimeDB.TimeDuration CompletionTime;
        [DataMember(Name = "MinCharacterLevel")]
        public uint MinCharacterLevel;

        public TaskTable(
            uint RowId,
            uint TaskId,
            string Name,
            string? Description,
            string? Type,
            uint LevelExpReward,
            uint SkillExpReward,
            System.Collections.Generic.List<uint> ItemRewards,
            SpacetimeDB.TimeDuration CompletionTime,
            uint MinCharacterLevel
        )
        {
            this.RowId = RowId;
            this.TaskId = TaskId;
            this.Name = Name;
            this.Description = Description;
            this.Type = Type;
            this.LevelExpReward = LevelExpReward;
            this.SkillExpReward = SkillExpReward;
            this.ItemRewards = ItemRewards;
            this.CompletionTime = CompletionTime;
            this.MinCharacterLevel = MinCharacterLevel;
        }

        public TaskTable()
        {
            this.Name = "";
            this.ItemRewards = new();
        }
    }
}
