// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Godot;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Textures: RefCounted
    {
        [DataMember(Name = "TextureID")]
        public uint TextureId;
        [DataMember(Name = "Name")]
        public string Name;
        [DataMember(Name = "Folder")]
        public string? Folder;

        public Textures(
            uint TextureId,
            string Name,
            string? Folder
        )
        {
            this.TextureId = TextureId;
            this.Name = Name;
            this.Folder = Folder;
        }

        public Textures()
        {
            this.Name = "";
        }
    }
}
