// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Godot;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class UserBanned: RefCounted
    {
        [DataMember(Name = "Identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "Entry_times")]
        public uint EntryTimes;
        [DataMember(Name = "First_entry_time")]
        public SpacetimeDB.Timestamp FirstEntryTime;
        [DataMember(Name = "Last_entry_time")]
        public SpacetimeDB.Timestamp LastEntryTime;
        [DataMember(Name = "Last_release_time")]
        public SpacetimeDB.Timestamp LastReleaseTime;
        [DataMember(Name = "Connection_tries")]
        public uint ConnectionTries;
        [DataMember(Name = "Last_connection_time")]
        public SpacetimeDB.Timestamp LastConnectionTime;
        [DataMember(Name = "reason")]
        public System.Collections.Generic.List<SubMessage> Reason;

        public UserBanned(
            SpacetimeDB.Identity Identity,
            uint EntryTimes,
            SpacetimeDB.Timestamp FirstEntryTime,
            SpacetimeDB.Timestamp LastEntryTime,
            SpacetimeDB.Timestamp LastReleaseTime,
            uint ConnectionTries,
            SpacetimeDB.Timestamp LastConnectionTime,
            System.Collections.Generic.List<SubMessage> Reason
        )
        {
            this.Identity = Identity;
            this.EntryTimes = EntryTimes;
            this.FirstEntryTime = FirstEntryTime;
            this.LastEntryTime = LastEntryTime;
            this.LastReleaseTime = LastReleaseTime;
            this.ConnectionTries = ConnectionTries;
            this.LastConnectionTime = LastConnectionTime;
            this.Reason = Reason;
        }

        public UserBanned()
        {
            this.Reason = new();
        }
    }
}
