// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Godot;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class UserInfo: RefCounted
    {
        [DataMember(Name = "Identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "Banned")]
        public bool Banned;
        [DataMember(Name = "Sus")]
        public bool Sus;
        [DataMember(Name = "Authenticated")]
        public bool Authenticated;
        [DataMember(Name = "Online")]
        public bool Online;
        [DataMember(Name = "last_reducer_call")]
        public SpacetimeDB.Timestamp LastReducerCall;

        public UserInfo(
            SpacetimeDB.Identity Identity,
            bool Banned,
            bool Sus,
            bool Authenticated,
            bool Online,
            SpacetimeDB.Timestamp LastReducerCall
        )
        {
            this.Identity = Identity;
            this.Banned = Banned;
            this.Sus = Sus;
            this.Authenticated = Authenticated;
            this.Online = Online;
            this.LastReducerCall = LastReducerCall;
        }

        public UserInfo()
        {
        }
    }
}
