// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Godot;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class UserMods: RefCounted
    {
        [DataMember(Name = "Identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "Mod_since")]
        public SpacetimeDB.Timestamp ModSince;

        public UserMods(
            SpacetimeDB.Identity Identity,
            SpacetimeDB.Timestamp ModSince
        )
        {
            this.Identity = Identity;
            this.ModSince = ModSince;
        }

        public UserMods()
        {
        }
    }
}
