// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Godot;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class User: RefCounted
    {
        [DataMember(Name = "Identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "User_id")]
        public uint UserId;
        [DataMember(Name = "Name")]
        public string? Name;
        [DataMember(Name = "Character_count")]
        public uint CharacterCount;
        [DataMember(Name = "First_login")]
        public SpacetimeDB.Timestamp FirstLogin;
        [DataMember(Name = "Last_login")]
        public SpacetimeDB.Timestamp LastLogin;
        [DataMember(Name = "LoginCount")]
        public uint LoginCount;

        public User(
            SpacetimeDB.Identity Identity,
            uint UserId,
            string? Name,
            uint CharacterCount,
            SpacetimeDB.Timestamp FirstLogin,
            SpacetimeDB.Timestamp LastLogin,
            uint LoginCount
        )
        {
            this.Identity = Identity;
            this.UserId = UserId;
            this.Name = Name;
            this.CharacterCount = CharacterCount;
            this.FirstLogin = FirstLogin;
            this.LastLogin = LastLogin;
            this.LoginCount = LoginCount;
        }

        public User()
        {
        }
    }
}
