// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ActiveTasksHandle : RemoteTableHandle<EventContext, ActiveTasks>
        {
            protected override string RemoteTableName => "ActiveTasks";

            public sealed class CharacterIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(ActiveTasks row) => row.CharacterId;

                public CharacterIdUniqueIndex(ActiveTasksHandle table) : base(table) { }
            }

            public readonly CharacterIdUniqueIndex CharacterId;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ActiveTasks row) => row.Id;

                public IdUniqueIndex(ActiveTasksHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ActiveTasksHandle(DbConnection conn) : base(conn)
            {
                CharacterId = new(this);
                Id = new(this);
            }

            protected override object GetPrimaryKey(ActiveTasks row) => row.Id;
        }

        public readonly ActiveTasksHandle ActiveTasks;
    }
}
