// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BaseExpTableHandle : RemoteTableHandle<EventContext, BaseExpTable>
        {
            protected override string RemoteTableName => "BaseExpTable";

            public sealed class LevelUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(BaseExpTable row) => row.Level;

                public LevelUniqueIndex(BaseExpTableHandle table) : base(table) { }
            }

            public readonly LevelUniqueIndex Level;

            internal BaseExpTableHandle(DbConnection conn) : base(conn)
            {
                Level = new(this);
            }

            protected override object GetPrimaryKey(BaseExpTable row) => row.Level;
        }

        public readonly BaseExpTableHandle BaseExpTable;
    }
}
