// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CharacterInventoryHandle : RemoteTableHandle<EventContext, CharacterInventory>
        {
            protected override string RemoteTableName => "CharacterInventory";

            public sealed class ItemIndex : BTreeIndexBase<(uint CharacterId, uint ItemId)>
            {
                protected override (uint CharacterId, uint ItemId) GetKey(CharacterInventory row) => (row.CharacterId, row.ItemId);

                public ItemIndex(CharacterInventoryHandle table) : base(table) { }
            }

            public readonly ItemIndex Item;

            public sealed class RowIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(CharacterInventory row) => row.RowId;

                public RowIdUniqueIndex(CharacterInventoryHandle table) : base(table) { }
            }

            public readonly RowIdUniqueIndex RowId;

            internal CharacterInventoryHandle(DbConnection conn) : base(conn)
            {
                Item = new(this);
                RowId = new(this);
            }

            protected override object GetPrimaryKey(CharacterInventory row) => row.RowId;
        }

        public readonly CharacterInventoryHandle CharacterInventory;
    }
}
