// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CharacterStatsHandle : RemoteTableHandle<EventContext, CharacterStats>
        {
            protected override string RemoteTableName => "CharacterStats";

            public sealed class StatIndex : BTreeIndexBase<(uint CharacterId, uint StatId)>
            {
                protected override (uint CharacterId, uint StatId) GetKey(CharacterStats row) => (row.CharacterId, row.StatId);

                public StatIndex(CharacterStatsHandle table) : base(table) { }
            }

            public readonly StatIndex Stat;

            public sealed class RowIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(CharacterStats row) => row.RowId;

                public RowIdUniqueIndex(CharacterStatsHandle table) : base(table) { }
            }

            public readonly RowIdUniqueIndex RowId;

            internal CharacterStatsHandle(DbConnection conn) : base(conn)
            {
                Stat = new(this);
                RowId = new(this);
            }

            protected override object GetPrimaryKey(CharacterStats row) => row.RowId;
        }

        public readonly CharacterStatsHandle CharacterStats;
    }
}
