// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CharacterSkillsHandle : RemoteTableHandle<EventContext, CharacterSkills>
        {
            protected override string RemoteTableName => "CharacterSkills";

            public sealed class SkillIndex : BTreeIndexBase<(uint CharacterId, uint SkillId)>
            {
                protected override (uint CharacterId, uint SkillId) GetKey(CharacterSkills row) => (row.CharacterId, row.SkillId);

                public SkillIndex(CharacterSkillsHandle table) : base(table) { }
            }

            public readonly SkillIndex Skill;

            public sealed class RowIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(CharacterSkills row) => row.RowId;

                public RowIdUniqueIndex(CharacterSkillsHandle table) : base(table) { }
            }

            public readonly RowIdUniqueIndex RowId;

            internal CharacterSkillsHandle(DbConnection conn) : base(conn)
            {
                Skill = new(this);
                RowId = new(this);
            }

            protected override object GetPrimaryKey(CharacterSkills row) => row.RowId;
        }

        public readonly CharacterSkillsHandle CharacterSkills;
    }
}
