// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CharacterHandle : RemoteTableHandle<EventContext, Character>
        {
            protected override string RemoteTableName => "Character";

            public sealed class CharacterIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Character row) => row.CharacterId;

                public CharacterIdUniqueIndex(CharacterHandle table) : base(table) { }
            }

            public readonly CharacterIdUniqueIndex CharacterId;

            public sealed class NameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(Character row) => row.Name;

                public NameUniqueIndex(CharacterHandle table) : base(table) { }
            }

            public readonly NameUniqueIndex Name;

            public sealed class GetUserIndex : BTreeIndexBase<(uint UserId, string Name)>
            {
                protected override (uint UserId, string Name) GetKey(Character row) => (row.UserId, row.Name);

                public GetUserIndex(CharacterHandle table) : base(table) { }
            }

            public readonly GetUserIndex GetUser;

            internal CharacterHandle(DbConnection conn) : base(conn)
            {
                CharacterId = new(this);
                Name = new(this);
                GetUser = new(this);
            }

            protected override object GetPrimaryKey(Character row) => row.CharacterId;
        }

        public readonly CharacterHandle Character;
    }
}
