// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ChatHandle : RemoteTableHandle<EventContext, Message>
        {
            protected override string RemoteTableName => "Chat";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Message row) => row.Id;

                public IdUniqueIndex(ChatHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ChatHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }
        }

        public readonly ChatHandle Chat;
    }
}
