// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DisallowedWordsHandle : RemoteTableHandle<EventContext, DisallowedWords>
        {
            protected override string RemoteTableName => "DisallowedWords";

            public sealed class WordUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(DisallowedWords row) => row.Word;

                public WordUniqueIndex(DisallowedWordsHandle table) : base(table) { }
            }

            public readonly WordUniqueIndex Word;

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(DisallowedWords row) => row.Id;

                public IdUniqueIndex(DisallowedWordsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal DisallowedWordsHandle(DbConnection conn) : base(conn)
            {
                Word = new(this);
                Id = new(this);
            }

            protected override object GetPrimaryKey(DisallowedWords row) => row.Word;
        }

        public readonly DisallowedWordsHandle DisallowedWords;
    }
}
