// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ItemTableHandle : RemoteTableHandle<EventContext, ItemTable>
        {
            protected override string RemoteTableName => "ItemTable";

            public sealed class ItemIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(ItemTable row) => row.ItemId;

                public ItemIdUniqueIndex(ItemTableHandle table) : base(table) { }
            }

            public readonly ItemIdUniqueIndex ItemId;

            public sealed class NameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(ItemTable row) => row.Name;

                public NameUniqueIndex(ItemTableHandle table) : base(table) { }
            }

            public readonly NameUniqueIndex Name;

            internal ItemTableHandle(DbConnection conn) : base(conn)
            {
                ItemId = new(this);
                Name = new(this);
            }

            protected override object GetPrimaryKey(ItemTable row) => row.ItemId;
        }

        public readonly ItemTableHandle ItemTable;
    }
}
