// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ModCommandsHandle : RemoteTableHandle<EventContext, ModCommands>
        {
            protected override string RemoteTableName => "ModCommands";

            public sealed class CommandUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(ModCommands row) => row.Command;

                public CommandUniqueIndex(ModCommandsHandle table) : base(table) { }
            }

            public readonly CommandUniqueIndex Command;

            internal ModCommandsHandle(DbConnection conn) : base(conn)
            {
                Command = new(this);
            }

            protected override object GetPrimaryKey(ModCommands row) => row.Command;
        }

        public readonly ModCommandsHandle ModCommands;
    }
}
