// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SkillTableHandle : RemoteTableHandle<EventContext, SkillTable>
        {
            protected override string RemoteTableName => "SkillTable";

            public sealed class NameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(SkillTable row) => row.Name;

                public NameUniqueIndex(SkillTableHandle table) : base(table) { }
            }

            public readonly NameUniqueIndex Name;

            public sealed class SkillIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(SkillTable row) => row.SkillId;

                public SkillIdUniqueIndex(SkillTableHandle table) : base(table) { }
            }

            public readonly SkillIdUniqueIndex SkillId;

            internal SkillTableHandle(DbConnection conn) : base(conn)
            {
                Name = new(this);
                SkillId = new(this);
            }

            protected override object GetPrimaryKey(SkillTable row) => row.SkillId;
        }

        public readonly SkillTableHandle SkillTable;
    }
}
