// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StatTableHandle : RemoteTableHandle<EventContext, StatTable>
        {
            protected override string RemoteTableName => "StatTable";

            public sealed class NameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(StatTable row) => row.Name;

                public NameUniqueIndex(StatTableHandle table) : base(table) { }
            }

            public readonly NameUniqueIndex Name;

            public sealed class StatIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(StatTable row) => row.StatId;

                public StatIdUniqueIndex(StatTableHandle table) : base(table) { }
            }

            public readonly StatIdUniqueIndex StatId;

            internal StatTableHandle(DbConnection conn) : base(conn)
            {
                Name = new(this);
                StatId = new(this);
            }

            protected override object GetPrimaryKey(StatTable row) => row.StatId;
        }

        public readonly StatTableHandle StatTable;
    }
}
