// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TaskRequirementTableHandle : RemoteTableHandle<EventContext, TaskRequirementTable>
        {
            protected override string RemoteTableName => "TaskRequirementTable";

            public sealed class RowIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(TaskRequirementTable row) => row.RowId;

                public RowIdUniqueIndex(TaskRequirementTableHandle table) : base(table) { }
            }

            public readonly RowIdUniqueIndex RowId;

            public sealed class RequirementsIndex : BTreeIndexBase<(uint TaskId, uint Id, string Type)>
            {
                protected override (uint TaskId, uint Id, string Type) GetKey(TaskRequirementTable row) => (row.TaskId, row.Id, row.Type);

                public RequirementsIndex(TaskRequirementTableHandle table) : base(table) { }
            }

            public readonly RequirementsIndex Requirements;

            internal TaskRequirementTableHandle(DbConnection conn) : base(conn)
            {
                RowId = new(this);
                Requirements = new(this);
            }

            protected override object GetPrimaryKey(TaskRequirementTable row) => row.RowId;
        }

        public readonly TaskRequirementTableHandle TaskRequirementTable;
    }
}
