// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TaskTableHandle : RemoteTableHandle<EventContext, TaskTable>
        {
            protected override string RemoteTableName => "TaskTable";

            public sealed class NameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(TaskTable row) => row.Name;

                public NameUniqueIndex(TaskTableHandle table) : base(table) { }
            }

            public readonly NameUniqueIndex Name;

            public sealed class RowIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(TaskTable row) => row.RowId;

                public RowIdUniqueIndex(TaskTableHandle table) : base(table) { }
            }

            public readonly RowIdUniqueIndex RowId;

            public sealed class TaskIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(TaskTable row) => row.TaskId;

                public TaskIdUniqueIndex(TaskTableHandle table) : base(table) { }
            }

            public readonly TaskIdUniqueIndex TaskId;

            internal TaskTableHandle(DbConnection conn) : base(conn)
            {
                Name = new(this);
                RowId = new(this);
                TaskId = new(this);
            }

            protected override object GetPrimaryKey(TaskTable row) => row.RowId;
        }

        public readonly TaskTableHandle TaskTable;
    }
}
