// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TaskRewardTableHandle : RemoteTableHandle<EventContext, TaskRewardTable>
        {
            protected override string RemoteTableName => "TaskRewardTable";

            public sealed class RowIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(TaskRewardTable row) => row.RowId;

                public RowIdUniqueIndex(TaskRewardTableHandle table) : base(table) { }
            }

            public readonly RowIdUniqueIndex RowId;

            public sealed class RewardsIndex : BTreeIndexBase<(uint TaskId, uint Id, string Type)>
            {
                protected override (uint TaskId, uint Id, string Type) GetKey(TaskRewardTable row) => (row.TaskId, row.Id, row.Type);

                public RewardsIndex(TaskRewardTableHandle table) : base(table) { }
            }

            public readonly RewardsIndex Rewards;

            internal TaskRewardTableHandle(DbConnection conn) : base(conn)
            {
                RowId = new(this);
                Rewards = new(this);
            }

            protected override object GetPrimaryKey(TaskRewardTable row) => row.RowId;
        }

        public readonly TaskRewardTableHandle TaskRewardTable;
    }
}
