// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class UserModsHandle : RemoteTableHandle<EventContext, UserMods>
        {
            protected override string RemoteTableName => "UserMods";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(UserMods row) => row.Identity;

                public IdentityUniqueIndex(UserModsHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal UserModsHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(UserMods row) => row.Identity;
        }

        public readonly UserModsHandle UserMods;
    }
}
