// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class UserInfoHandle : RemoteTableHandle<EventContext, UserInfo>
        {
            protected override string RemoteTableName => "UserInfo";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(UserInfo row) => row.Identity;

                public IdentityUniqueIndex(UserInfoHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal UserInfoHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(UserInfo row) => row.Identity;
        }

        public readonly UserInfoHandle UserInfo;
    }
}
